### ISSUE TITLE
Problem with loading the model

### ISSUE THREAD

**Issue by Panbug** [tusabez/KITT_AI_Python#1]
While trying to run the program I get the error below on my RPi 4B. Where do I get that melspectrogram.onnx? I've installed openwakeword by just "pip install openwakeword" is it the wrong one?

> bulbulator@raspberrypi:~/KITT_AI_Python $ python3 KITT_Pi.py 
> Current working directory: /home/bulbulator/KITT_AI_Python
> Traceback (most recent call last):
>   File "/home/bulbulator/KITT_AI_Python/KITT_Pi.py", line 138, in <module>
>     detector = Model(wakeword_models=["hey_kitt.onnx"], inference_framework='onnx')
>   File "/home/bulbulator/.local/lib/python3.9/site-packages/openwakeword/utils.py", line 686, in wrapped
>     return func(*args, **new_kwargs)
>   File "/home/bulbulator/.local/lib/python3.9/site-packages/openwakeword/model.py", line 213, in __init__
>     self.preprocessor = AudioFeatures(inference_framework=inference_framework, **kwargs)
>   File "/home/bulbulator/.local/lib/python3.9/site-packages/openwakeword/utils.py", line 84, in __init__
>     self.melspec_model = ort.InferenceSession(melspec_model_path, sess_options=sessionOptions,
>   File "/home/bulbulator/.local/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
>     self._create_inference_session(providers, provider_options, disabled_optimizers)
>   File "/home/bulbulator/.local/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 480, in _create_inference_session
>     sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
> onnxruntime.capi.onnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from /home/bulbulator/.local/lib/python3.9/site-packages/openwakeword/resources/models/melspectrogram.onnx failed:Load model /home/bulbulator/.local/lib/python3.9/site-packages/openwakeword/resources/models/melspectrogram.onnx failed. File doesn't exist

**Comment by tusabez** [comment]
Make sure to run models.py so it will install the rest of the necessary files.
